# General render settings
[renderer]
    # Base ambient color
    ambient = [0.15, 0.15, 0.15]
    # Specular power
    spec_power = 10.0
    # Background clear color
    clear_color = "6495ED"

# World definition
[world]
    ###################
    # World's objects #
    ###################
    [[world.objects]]
        name = "monkey"
        obj = "Scenes/Objects/monkey.toml"

    [[world.objects]]
        name = "cube"
        obj = "Scenes/Objects/cube.toml"

    #####################
    # Entity transforms #
    #####################
    [[world.transforms]]
        name = "monkey_trans"
        position = [0.0, 0.0, -2.0]

    [[world.transforms]]
        name = "cube_trans"
        position = [0.0, 0.0, 2.0]

    ####################
    # World's entities #
    ####################
    [[world.entities]]
        wobj = "monkey"
        transform = "monkey_trans"

    [[world.entities]]
        wobj = "cube"
        transform = "cube_trans"
